const list = [
    {
      id: 1,
      title: "Black Hoodie",
      type:"Hoodie",
      color: "Black",
      price: 1889,
      stock:"🙂 In Stock",
      size:"XL",
      img: "https://m.media-amazon.com/images/I/51ZIqCyzpbL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Red Hoodie",
      type:"Hoodie",
      color: "Red",
      price: 1998,
      stock:"🙂 In Stock",
      size:"XXL",
      img: "https://m.media-amazon.com/images/I/61j2p9Q2LcL._UX569_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Green Hoodie",
      type:"Hoodie",
      color: "Green",
      price: 1430,
      stock:"🙂 In Stock",
      size:"L",
      img: "https://m.media-amazon.com/images/I/31IeVTDUc-L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Blue Hoodie",
      type:"Hoodie",
      color: "Blue",
      price: 1570,
      stock:"🙂 In Stock",
      size:"M",
      img: "https://m.media-amazon.com/images/I/51xidn159hL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "printed shirt",
      type:"Shirt",
      color: "Blue",
      price: 1499,
      stock:"🙂 In Stock",
      size:"S",
      img: "https://m.media-amazon.com/images/I/51JIFyIdHmS._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },

    /*--------------------------------------------------------------------------------------------------------------------------*/
    {
      id: 6,
      title: "Full Sleeves shirt",
      type:"Shirt",
      color: "Gray",
      price: 2499,
      stock:"🙂 In Stock",
      size:"S",
      img: "https://m.media-amazon.com/images/I/71GnzCoqDdL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "T-shirt",
      type:"T-Shirt",
      color: "Brown",
      price: 1499,
      stock:"🙂 In Stock",
      size:"M",
      img: "https://m.media-amazon.com/images/I/71HlCrnS7DL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Hulk T-shirt",
      type:"T-Shirt",
      color: "Green",
      price: 1399,
      stock:"🙂 In Stock",
      size:"XL",
      img: "https://m.media-amazon.com/images/I/61lINUSCagL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Spider-Man T-shirt",
      type:"T-Shirt",
      color: "Red",
      price: 1899,
      stock:"🙂 In Stock",
      size:"L",
      img: "https://m.media-amazon.com/images/I/510vXWbKEHL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Denim Jacket",
      type:"Jacket",
      color: "Blue",
      price: 1999,
      stock:"🙂 In Stock",
      size:"XXL",
      img: "https://m.media-amazon.com/images/I/71OxRcqGzkL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
  
  ];
  
  export default list;